
package introsde.meteoadapter.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MeteoService", targetNamespace = "http://soap.meteoadapter.introsde/", wsdlLocation = "http://meteoadapter.herokuapp.com/?wsdl")
public class MeteoService
    extends Service
{

    private final static URL METEOSERVICE_WSDL_LOCATION;
    private final static WebServiceException METEOSERVICE_EXCEPTION;
    private final static QName METEOSERVICE_QNAME = new QName("http://soap.meteoadapter.introsde/", "MeteoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://meteoadapter.herokuapp.com/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        METEOSERVICE_WSDL_LOCATION = url;
        METEOSERVICE_EXCEPTION = e;
    }

    public MeteoService() {
        super(__getWsdlLocation(), METEOSERVICE_QNAME);
    }

    public MeteoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), METEOSERVICE_QNAME, features);
    }

    public MeteoService(URL wsdlLocation) {
        super(wsdlLocation, METEOSERVICE_QNAME);
    }

    public MeteoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, METEOSERVICE_QNAME, features);
    }

    public MeteoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MeteoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MeteoAdapter
     */
    @WebEndpoint(name = "MeteoAdapterImplPort")
    public MeteoAdapter getMeteoAdapterImplPort() {
        return super.getPort(new QName("http://soap.meteoadapter.introsde/", "MeteoAdapterImplPort"), MeteoAdapter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MeteoAdapter
     */
    @WebEndpoint(name = "MeteoAdapterImplPort")
    public MeteoAdapter getMeteoAdapterImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.meteoadapter.introsde/", "MeteoAdapterImplPort"), MeteoAdapter.class, features);
    }

    private static URL __getWsdlLocation() {
        if (METEOSERVICE_EXCEPTION!= null) {
            throw METEOSERVICE_EXCEPTION;
        }
        return METEOSERVICE_WSDL_LOCATION;
    }

}
