
package introsde.meteoadapter.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MeteoAdapter", targetNamespace = "http://soap.meteoadapter.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MeteoAdapter {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns introsde.meteoadapter.soap.Meteo
     */
    @WebMethod
    @WebResult(name = "getMeteo", targetNamespace = "")
    @RequestWrapper(localName = "getMeteo", targetNamespace = "http://soap.meteoadapter.introsde/", className = "introsde.meteoadapter.soap.GetMeteo")
    @ResponseWrapper(localName = "getMeteoResponse", targetNamespace = "http://soap.meteoadapter.introsde/", className = "introsde.meteoadapter.soap.GetMeteoResponse")
    @Action(input = "http://soap.meteoadapter.introsde/MeteoAdapter/getMeteoRequest", output = "http://soap.meteoadapter.introsde/MeteoAdapter/getMeteoResponse")
    public Meteo getMeteo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
