
package introsde.mapsadapter.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MapsAdapter", targetNamespace = "http://soap.mapsadapter.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MapsAdapter {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns introsde.mapsadapter.soap.Maps
     */
    @WebMethod
    @WebResult(name = "getMaps", targetNamespace = "")
    @RequestWrapper(localName = "getMaps", targetNamespace = "http://soap.mapsadapter.introsde/", className = "introsde.mapsadapter.soap.GetMaps")
    @ResponseWrapper(localName = "getMapsResponse", targetNamespace = "http://soap.mapsadapter.introsde/", className = "introsde.mapsadapter.soap.GetMapsResponse")
    @Action(input = "http://soap.mapsadapter.introsde/MapsAdapter/getMapsRequest", output = "http://soap.mapsadapter.introsde/MapsAdapter/getMapsResponse")
    public Maps getMaps(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
