
package introsde.mapsadapter.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MapsService", targetNamespace = "http://soap.mapsadapter.introsde/", wsdlLocation = "http://mapsadapter.herokuapp.com/?wsdl")
public class MapsService
    extends Service
{

    private final static URL MAPSSERVICE_WSDL_LOCATION;
    private final static WebServiceException MAPSSERVICE_EXCEPTION;
    private final static QName MAPSSERVICE_QNAME = new QName("http://soap.mapsadapter.introsde/", "MapsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://mapsadapter.herokuapp.com/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MAPSSERVICE_WSDL_LOCATION = url;
        MAPSSERVICE_EXCEPTION = e;
    }

    public MapsService() {
        super(__getWsdlLocation(), MAPSSERVICE_QNAME);
    }

    public MapsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MAPSSERVICE_QNAME, features);
    }

    public MapsService(URL wsdlLocation) {
        super(wsdlLocation, MAPSSERVICE_QNAME);
    }

    public MapsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MAPSSERVICE_QNAME, features);
    }

    public MapsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MapsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MapsAdapter
     */
    @WebEndpoint(name = "MapsAdapterImplPort")
    public MapsAdapter getMapsAdapterImplPort() {
        return super.getPort(new QName("http://soap.mapsadapter.introsde/", "MapsAdapterImplPort"), MapsAdapter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MapsAdapter
     */
    @WebEndpoint(name = "MapsAdapterImplPort")
    public MapsAdapter getMapsAdapterImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.mapsadapter.introsde/", "MapsAdapterImplPort"), MapsAdapter.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MAPSSERVICE_EXCEPTION!= null) {
            throw MAPSSERVICE_EXCEPTION;
        }
        return MAPSSERVICE_WSDL_LOCATION;
    }

}
